version: "3.8"

services:
  jjsmartexam:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/App
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
